<?php

declare(strict_types=1);

namespace Mosyca\Core\Bridge;

use Mosyca\Core\Action\ActionRegistry;
use Mosyca\Core\Resource\ResourceRegistry;

/**
 * MCP tool discovery service for the PHP-native Bridge (V0.13 — ADR 3.1 + 3.2).
 *
 * Implements the `list_tools` side of the MCP Bridge by iterating the ResourceRegistry
 * directly — bypassing REST routing and API Platform entirely (ADR 3.1).
 *
 * Tool names follow the flat MCP nomenclature (ADR 3.2):
 *   {pluginNamespace}_{resourceName}_{operationSlug}
 *   e.g. "core_system_ping", "shopware6_order_get-margin"
 *
 * Each tool's JSON Schema is generated by ConstraintSchemaTranslator, which:
 *   - Translates ActionInterface::getParameters() into JSON Schema Draft-07
 *   - Injects the required `tenant` parameter (ADR 3.4)
 *
 * @see ConstraintSchemaTranslator
 * @see McpExecutionService
 * @see ResourceRegistry
 */
final readonly class McpDiscoveryService
{
    public function __construct(
        private ResourceRegistry $resourceRegistry,
        private ActionRegistry $actionRegistry,
        private ConstraintSchemaTranslator $translator,
    ) {
    }

    /**
     * Build the MCP list_tools payload from all registered resources.
     *
     * Each operation in every AbstractResource becomes one MCP tool entry.
     * The tenant parameter is injected into every tool schema (ADR 3.4).
     *
     * @param string[] $tenantEnum Available tenant IDs (empty = required string, no enum constraint)
     *
     * @return array<int, array{name: string, description: string, inputSchema: array<string, mixed>}>
     */
    public function listTools(array $tenantEnum = []): array
    {
        /** @var array<int, array{name: string, description: string, inputSchema: array<string, mixed>}> $tools */
        $tools = [];

        foreach ($this->resourceRegistry->all() as $resource) {
            $ns = $resource->getPluginNamespace();
            $resName = $resource->getName();

            foreach ($resource->getOperations() as $opSlug => $opDef) {
                // ADR 3.2: flat tool name
                $toolName = $ns.'_'.$resName.'_'.$opSlug;

                // Resolve the live Action instance by its FQCN (same as REST gateway).
                $action = $this->actionRegistry->getByClass($opDef['action']);

                $tools[] = [
                    'name' => $toolName,
                    'description' => $action->getDescription(),
                    'inputSchema' => $this->translator->translate(
                        $action->getParameters(),
                        $tenantEnum,
                    ),
                ];
            }
        }

        return $tools;
    }
}
