<?php

declare(strict_types=1);

namespace Mosyca\Core\Bridge\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Mosyca\Core\Bridge\TenantSession\TenantSession;
use Mosyca\Core\Bridge\TenantSession\TenantSessionRepository;
use Mosyca\Core\Bridge\TenantSession\TenantSessionState;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\UriSigner;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Csrf\CsrfToken;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use Twig\Environment;

/**
 * Human-facing approval endpoint for OOB-CA tenant session requests.
 *
 * GET  /api/v1/mcp/session/{jti}/approve?_hash=...&_expiration=...
 *   → Renders an approve/deny form (HTML). Requires valid UriSigner signature.
 *
 * POST /api/v1/mcp/session/{jti}/approve?_hash=...&_expiration=...
 *   → Validates CSRF token, transitions TenantSession state, renders confirmation page.
 *
 * SECURITY (SR-OOB-2, SR-OOB-3):
 * - GET + POST URLs MUST carry a valid UriSigner signature (_hash + _expiration params).
 *   Invalid or expired URLs return 403 — the DB is never accessed.
 * - POST forms MUST include a valid CSRF token (_csrf_token field).
 * - The approval URL is generated by TenantSessionApprovalUrlGenerator (TTL = 600 s).
 */
#[Route('/api/v1/mcp/session/{jti}/approve', name: 'mosyca_tenant_session_approve', methods: ['GET', 'POST'])]
final class TenantSessionApprovalController
{
    public function __construct(
        private readonly TenantSessionRepository $repository,
        private readonly UriSigner $uriSigner,
        private readonly EntityManagerInterface $entityManager,
        private readonly Environment $twig,
        private readonly CsrfTokenManagerInterface $csrfTokenManager,
    ) {
    }

    public function __invoke(Request $request, string $jti): Response
    {
        // SR-OOB-2: Verify signed URL before any DB access.
        if (!$this->uriSigner->checkRequest($request)) {
            return new Response(
                'Invalid or expired approval link.',
                Response::HTTP_FORBIDDEN,
                ['Content-Type' => 'text/plain; charset=UTF-8'],
            );
        }

        $session = $this->repository->findByJti($jti);

        // Session not found, already decided, or expired — show "too late" page.
        if (null === $session
            || TenantSessionState::PENDING !== $session->getState()
            || $session->isExpired()
        ) {
            return $this->renderPage(
                ['expired' => true, 'jti' => $jti, 'session' => $session],
                Response::HTTP_GONE,
            );
        }

        if ($request->isMethod('POST')) {
            return $this->handlePost($request, $session, $jti);
        }

        // GET: render approval form.
        return $this->renderPage([
            'session' => $session,
            'csrf_token' => $this->csrfTokenManager->getToken('tenant_session_'.$jti)->getValue(),
            'jti' => $jti,
        ]);
    }

    private function handlePost(Request $request, TenantSession $session, string $jti): Response
    {
        // SR-OOB-3: Validate CSRF token.
        $csrfToken = new CsrfToken('tenant_session_'.$jti, $request->request->getString('_csrf_token'));

        if (!$this->csrfTokenManager->isTokenValid($csrfToken)) {
            return new Response(
                'Invalid CSRF token.',
                Response::HTTP_UNPROCESSABLE_ENTITY,
                ['Content-Type' => 'text/plain; charset=UTF-8'],
            );
        }

        $action = $request->request->getString('action');

        if ('approve' === $action) {
            $session->approve();
        } elseif ('deny' === $action) {
            $session->deny();
        } else {
            return new Response(
                'Invalid action. Expected "approve" or "deny".',
                Response::HTTP_BAD_REQUEST,
                ['Content-Type' => 'text/plain; charset=UTF-8'],
            );
        }

        $this->entityManager->flush();

        return $this->renderPage([
            'confirmed' => true,
            'approved' => 'approve' === $action,
            'session' => $session,
            'jti' => $jti,
        ]);
    }

    /**
     * @param array<string, mixed> $vars
     */
    private function renderPage(array $vars, int $statusCode = Response::HTTP_OK): Response
    {
        return new Response(
            $this->twig->render('bridge/tenant_session_approval.html.twig', $vars),
            $statusCode,
            ['Content-Type' => 'text/html; charset=UTF-8'],
        );
    }
}
